name: API Auto Test CI

on:
  push:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 启动 mock_server
        run: |
          nohup python mock_server.py &

      - name: 等待服务启动
        run: sleep 5

      - name: 运行测试
        run: |
          pytest testcases/ --maxfail=1 --disable-warnings